(define (dbl_atm a l)
  (if (null? l)
    '()
    (if (list? l)
      (if (list? (car l))
        (append (list (dbl_atm a (car l))) (dbl_atm a (cdr l)))
        (append (dbl_atm a (car l)) (dbl_atm a (cdr l)))
      )
      (if (equal? a l)
        (append (list l) (list l))
        (list l)
      )
    )
  )
)

(dbl_atm 'a '(a (b c a (a d))))